### PR TITLE
T2P-33 updated branch [heart & comment]

### PR DESCRIPTION
**Pull request by JeH9o**
User should be able heart and comment.
Comments are listed under the text field.

### CODE REVIEW

**Comment by JeH9o** [comment]
DON'T MERGE IT YET! My tests were not added.

**Comment by hannaperez** [comment]
DO NOT MERGE YET

**Comment by JeH9o** [comment]
Since my environment may cause problems so I can't actually run the tests and see results although I added tests. I will check the test details again tomorrow.

**Comment by JeH9o** [comment]
CAN MERGE

**Review by elviazamora338 — APPROVED** [review]
lgtm

**Pull request merged**
